apiVersion: v1
kind: ConfigMap
metadata:
  name: zk-cfg
data:
  zoo.cfg: |
    dataDir=/data
    dataLogDir=/datalog
    tickTime=2000
    initLimit=5
    syncLimit=2
    autopurge.snapRetainCount=3
    autopurge.purgeInterval=0
    maxClientCnxns=60
    standaloneEnabled=false
    reconfigEnabled=true
    skipACL=yes
    admin.enableServer=true  
  mkconfig.sh: |
    #!/bin/sh
    podname=${POD_NAME}
    namespace=${NAMESPACE}
    myid=$((${POD_NAME##*-}+1))
    svcname=${POD_NAME%-*}
    echo $myid > /data/myid
    cp /tmp/zoo.cfg.tpl /conf/zoo.cfg
    for id in `seq 1 3`
    do
      echo -e "server."$id"=$svcname-"$(($id-1))".$svcname.$namespace:2888:3888;2181" >> /conf/zoo.cfg
    done
    if [ $myid -gt 3 ];then
      echo -e "server."$myid"="$podname".$svcname.$namespace:2888:3888;2181" >> /conf/zoo.cfg
    fi
    echo "======"
    cat /conf/zoo.cfg
    echo "======"
    sleep 10

